[project]
name = "ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Richang Sharma", email = "jedirichang@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
ai-engineering = "ai_engineering.main:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
